"""Add tables

Revision ID: e9bdf9993f07
Revises: 
Create Date: 2020-08-02 20:29:16.547406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9bdf9993f07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_type',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('eid', sa.Unicode(), nullable=False),
    sa.Column('type', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('eid'),
    sa.UniqueConstraint('type')
    )
    op.create_table('entity_type_definition',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('eid', sa.Unicode(), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entity_type_eid', sa.Unicode(), nullable=False),
    sa.ForeignKeyConstraint(['entity_type_eid'], ['entity_type.eid'], ),
    sa.PrimaryKeyConstraint('eid'),
    sa.UniqueConstraint('entity_type_eid', 'version', name='entity_type_definition_uq')
    )
    op.create_table('node',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('eid', sa.Unicode(), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('definition_eid', sa.Unicode(), nullable=False),
    sa.ForeignKeyConstraint(['definition_eid'], ['entity_type_definition.eid'], ),
    sa.PrimaryKeyConstraint('eid')
    )
    op.create_table('relation',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('eid', sa.Unicode(), nullable=False),
    sa.Column('node_to_eid', sa.Unicode(), nullable=False),
    sa.Column('node_from_eid', sa.Unicode(), nullable=False),
    sa.Column('label', sa.Unicode(), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['node_from_eid'], ['node.eid'], ),
    sa.ForeignKeyConstraint(['node_to_eid'], ['node.eid'], ),
    sa.PrimaryKeyConstraint('eid', 'node_to_eid', 'node_from_eid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation')
    op.drop_table('node')
    op.drop_table('entity_type_definition')
    op.drop_table('entity_type')
    # ### end Alembic commands ###
